# Generated by Django 4.2 on 2023-05-06 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmroom",
            name="users",
            field=models.ManyToManyField(
                related_name="DMRooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="DMs",
                to="dms.dmroom",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="DMs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
