# Generated by Django 4.2 on 2023-04-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DMs', to='dms.dmroom'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DMs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dmroom',
            name='users',
            field=models.ManyToManyField(related_name='DMRooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
