# Generated by Django 4.2 on 2023-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amenities", "0002_initial"),
        ("houses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="houses", to="amenities.amenity"
            ),
        ),
    ]
