# Generated by Django 4.2 on 2023-04-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(related_name='houses', to='houses.amenity'),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='house',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
