# Generated by Django 4.2 on 2023-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amenities", "0003_alter_amenity_host"),
        ("experiences", "0003_alter_experience_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="experiences", to="amenities.amenity"
            ),
        ),
    ]
