# Generated by Django 4.2 on 2023-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[("house", "House"), ("experience", "Experience")],
                max_length=15,
            ),
        ),
    ]
