# Generated by Django 4.2 on 2023-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("detail", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent",
                    models.CharField(
                        choices=[("house", "House"), ("experience", "Experience")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
    ]
