# Generated by Django 4.2 on 2023-05-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("amenities", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amenities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
